### ISSUE TITLE
希望重新看到渠道key

### ISSUE THREAD

**Issue by c121914yu** [songquanpeng/one-api#380]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**

由于现在封号频繁，批量导入几个号后，其中部分被封了，又看不到对应的key，排查起来麻烦。希望给个简单的途径可以看到原本的key

**应用场景**

**Comment by songquanpeng** [comment]
可以直接搜索



---Original---
From: ***@***.***&gt;
Sent at: 2023年8月10日(Thu) AM9:22
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [songquanpeng/one-api] 希望重新看到渠道key (Issue #380)




 
例行检查
  
 我已确认目前没有类似 issue
 
 我已确认我已升级到最新版本
 
 我已完整查看过项目 README，已确定现有版本无法满足需求
 
 我理解并愿意跟进此 issue，协助测试和提供反馈
 
 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭
  
功能描述
 
由于现在封号频繁，批量导入几个号后，其中几个被封了，又看不到对应的key，排查起来麻烦。希望给个简单的途径可以看到原本的key
 
应用场景

**Comment by c121914yu** [comment]
> 可以直接搜索
> […](#)
> ---Original--- From: ***@***.***&gt; Sent at: 2023年8月10日(Thu) AM9:22 To: ***@***.***&gt;; Cc: ***@***.***&gt;; Subject: [songquanpeng/one-api] 希望重新看到渠道key (Issue #380) 例行检查 我已确认目前没有类似 issue 我已确认我已升级到最新版本 我已完整查看过项目 README，已确定现有版本无法满足需求 我理解并愿意跟进此 issue，协助测试和提供反馈 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭 功能描述 由于现在封号频繁，批量导入几个号后，其中几个被封了，又看不到对应的key，排查起来麻烦。希望给个简单的途径可以看到原本的key 应用场景 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

搜索确实可以，，但是比如我10个号，封了2个，，搜起来也很麻烦~ 感觉可以给被禁用的渠道一个特殊操作。。

**Comment by songquanpeng** [comment]
渠道测试不能用么



---Original---
From: ***@***.***&gt;
Sent at: 2023年8月10日(Thu) AM9:25
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [songquanpeng/one-api] 希望重新看到渠道key (Issue #380)




  
可以直接搜索
 …
 ---Original--- From: @.&gt; Sent at: 2023年8月10日(Thu) AM9:22 To: @.&gt;; Cc: @.&gt;; Subject: [songquanpeng/one-api] 希望重新看到渠道key (Issue #380) 例行检查 我已确认目前没有类似 issue 我已确认我已升级到最新版本 我已完整查看过项目 README，已确定现有版本无法满足需求 我理解并愿意跟进此 issue，协助测试和提供反馈 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭 功能描述 由于现在封号频繁，批量导入几个号后，其中几个被封了，又看不到对应的key，排查起来麻烦。希望给个简单的途径可以看到原本的key 应用场景 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.&gt;
  
搜索确实可以，，但是比如我10个号，封了2个，，搜起来也很麻烦~ 感觉可以给被禁用的渠道一个特殊操作。。

**Comment by c121914yu** [comment]
> 渠道测试不能用么

不是，我主要是想能找到被禁用的key（被封的）

**Comment by ckt1031** [comment]
直接把數據庫Bump到本地（xxx.sql）
那麼你就可以直接查看Key了

**Comment by songquanpeng** [comment]
1. 如果已知哪一个key被封了，可以直接搜索key找到对应渠道
2. 否则使用测试所有渠道的功能自动禁用掉失效渠道

**Comment by songquanpeng** [comment]
前端不展示主要是为了安全

**Comment by c121914yu** [comment]
> 1. 如果已知哪一个key被封了，可以直接搜索key找到对应渠道

就是不知道哪个被封了，是想知道哪个被封了，可以找到那个被封的key

**Comment by songquanpeng** [comment]
我考虑一下把 key 传到前端的风险。

**Comment by zeylei** [comment]
> 我考虑一下把 key 传到前端的风险。

你不需要把key传到前端，你只需要把部分key传到前端即可（如：后4位/前4位）。openai在封号的时候，会告诉客户端出问题的key的后四位。只要知道这后四位，就可以方便排查了。
